trigger:
  branches:
    include:
      - dev

pool:
  name: 'local_pool' 

variables:
  - group: 'GITHUB_TOKEN'

jobs:
  - job: InstallDependencies
    displayName: 'Install Dependencies'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          addToPath: true

      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        displayName: 'Install dependencies'
        env:
          GITHUB_TOKEN: $(GITHUB_TOKEN) 

  - job: LintCode
    displayName: 'Run Linter'
    dependsOn: InstallDependencies
    steps:
      - script: |
          flake8 .
        displayName: 'Run Linter'

  - job: RunTests
    displayName: 'Run Tests'
    dependsOn: LintCode
    steps:
      - script: |
          python -m unittest discover
        displayName: 'Run tests'
